apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jxhr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jxhr
    app.kubernetes.io/part-of: byoc-app-cmxe
  name: jxhr
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: jxhr
status:
  loadBalancer: {}
